/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNISample */

#include "MCodec.h"

#include <stdio.h>
#include <android/log.h>

#ifndef _Included_JNISample
#define _Included_JNISample
#ifdef __cplusplus
extern "C" {
#endif

MCodec m_codec;

/// ================================================================ //
///
/// ================================================================ //

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_YuvNV21toRGB(
        JNIEnv *env,
        jobject,
        jintArray rgba_result,
        jbyteArray yuv,
        jint width,
        jint height);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_YuvNV21FlipHorizontal(
		JNIEnv *env,
		jobject,
		jbyteArray yuv,
		jint width,
		jint height);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_YuvNV21FlipVertical(
		JNIEnv *env,
		jobject,
		jbyteArray yuv,
		jint width,
		jint height);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_YuvNV21RotateLeft(
		JNIEnv *env,
		jobject,
		jbyteArray yuv,
		jint width,
		jint height);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_YuvNV21RotateRight(
		JNIEnv *env,
		jobject,
		jbyteArray yuv,
		jint width,
		jint height);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_YuvNV21RotateDown(
		JNIEnv *env,
		jobject,
		jbyteArray yuv,
		jint width,
		jint height);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_releaseBuffer(
		JNIEnv *env,
		jobject);


JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_flipHorizontal(
		JNIEnv *env,
		jobject,
		jintArray rgba_img,
		jint width,
		jint height);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_flipVertical(
		JNIEnv *env,
		jobject,
		jintArray rgba_img,
		jint width,
		jint height);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_rotateLeft(
		JNIEnv *env,
		jobject,
		jintArray rgba_img,
		jint width,
		jint height);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_rotateRight(
		JNIEnv *env,
		jobject,
		jintArray rgba_img,
		jint width,
		jint height);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_rotateDown(
		JNIEnv *env,
		jobject,
		jintArray rgba_img,
		jint width,
		jint height);

/// ================================================================ //
///          					ENCODE/DECODE
/// ================================================================ //
JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_ENCODEinit(
		JNIEnv *env,
		jobject,
		jint width,
		jint height,
		jint encode_level);

#ifdef __cplusplus
}
#endif
#endif
