/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNISample */

#include <stdio.h>
#include <android/log.h>

#ifndef _Included_JNISample
#define _Included_JNISample
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_stringFromJNI(
        JNIEnv *env,
        jobject);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_square(
        JNIEnv *env,
        jobject,
        jint num);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_YuvNV21toRGB(
        JNIEnv *env,
        jobject,
        jintArray rgba_result,
        jbyteArray yuv,
        jint width,
        jint height);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_YuvNV21FlipHorizontal(
		JNIEnv *env,
		jobject,
		jbyteArray yuv,
		jint width,
		jint height);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_YuvNV21FlipVertical(
		JNIEnv *env,
		jobject,
		jbyteArray yuv,
		jint width,
		jint height);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_YuvNV21RotateLeft(
		JNIEnv *env,
		jobject,
		jbyteArray yuv,
		jint width,
		jint height);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_YuvNV21RotateRight(
		JNIEnv *env,
		jobject,
		jbyteArray yuv,
		jint width,
		jint height);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_YuvNV21RotateDown(
		JNIEnv *env,
		jobject,
		jbyteArray yuv,
		jint width,
		jint height);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_flipHorizontal(
		JNIEnv *env,
		jobject,
		jintArray rgba_img,
		jint width,
		jint height);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_flipVertical(
		JNIEnv *env,
		jobject,
		jintArray rgba_img,
		jint width,
		jint height);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_rotateLeft(
		JNIEnv *env,
		jobject,
		jintArray rgba_img,
		jint width,
		jint height);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_rotateRight(
		JNIEnv *env,
		jobject,
		jintArray rgba_img,
		jint width,
		jint height);

JNIEXPORT jint JNICALL Java_com_hanhnv_JNI2_rotateDown(
		JNIEnv *env,
		jobject,
		jintArray rgba_img,
		jint width,
		jint height);

//public static native int YuvFlipHorizontal(byte[]yuv, int width, int height);
//public static native int YuvFlipVertical(byte[]yuv, int width, int height);
//public static native int YuvRotateLeft(byte[]yuv, int width, int height);
//public static native int YuvRotateRight(byte[]yuv, int width, int height);
//public static native int YuvRotateDown(byte[]yuv, int width, int height);
//public static native int rotateRight(int[]rgba_img, int width, int height);
//public static native int rotateLeft(int[]rgba_img, int width, int height);
//public static native int flipHorizontal(int[]rgba_img, int width, int height);
//public static native int flipVertical(int[]rgba_img, int width, int height);
//public static native int RotateRGB(int[] rgba_img, int width, int height);
//public static native void Test2(int[] rgb_result, byte[]raw_data);

JNIEXPORT jintArray JNICALL Java_com_hanhnv_JNI2_Test(
		JNIEnv *env,
		jobject,
		jbyteArray data);

JNIEXPORT void JNICALL Java_com_hanhnv_JNI2_Test2(
		JNIEnv *env,
		jobject,
		jintArray result,
		jbyteArray raw);

#ifdef __cplusplus
}
#endif
#endif
